# -*- coding: utf-8 -*-
"""AP Research Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1roL3EOGdq_cTKTgRLiWV2OZtZP4d68jp
"""

from keras.models import Sequential
from keras.layers import Conv2D, Flatten, Dense, Dropout, Reshape
from keras.src.callbacks import EarlyStopping
from sklearn.model_selection import KFold
from sklearn.datasets import load_breast_cancer
from tensorflow import keras
from keras import layers
from matplotlib import pyplot
from sklearn.preprocessing import StandardScaler, LabelBinarizer
from sklearn.model_selection import train_test_split
import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from scipy.stats import wilcoxon
import pandas as pd

# Global declaration: how many times to run or whether of not to run
number_of_kfold = 10
num_epochs_for_kfold = 100
num_epochs_for_final = 100
print_summary_decision = True
do_kfold_decision = True
early_stopping_decision = True


# CNN Model
class cnnPredictionModel:

    # Method to initialize the model
    def __init__(self):
        """ init function
        :param:
        :return:
        """

        # Loading dataset
        self.data = load_breast_cancer()
        x = self.data.data      # shape (569, 30)
        y = self.data.target    # 0 or 1 (malignant/benign)

        # Standardize features
        scaler = StandardScaler()
        x_scaled = scaler.fit_transform(x)

        # Reshape for CNN: interpret as 5x6 "images" with 1 channel (since CNN expects 2D data)
        self.X_reshaped = x_scaled.reshape(-1, 5, 6, 1)

        # One-hot encode labels
        lb = LabelBinarizer()
        self.y_onehot = lb.fit_transform(y)

        self.callback = EarlyStopping(
            monitor='val_loss',
            patience=3,
            restore_best_weights=True
        )

        # Storage for metrics
        self.kfold_loss = []
        self.kfold_acc = []
        self.kfold_report = []
        self.final_report = []

    # Method for returning the model's metric
    def get_metrics(self):
        return self.kfold_loss, self.kfold_acc, self.kfold_report, self.final_report

    # Method for plotting loss value for training and validation
    @staticmethod
    def plot_loss_history(history):

        # Plot loss values captured during model training
        pyplot.plot(history.history['loss'], label='Training Dataset')
        pyplot.plot(history.history['val_loss'], label='Testing Dataset')
        pyplot.title('CNN Epoch Loss History')
        pyplot.legend(("loss", "val_loss"), loc='upper right', shadow=True)
        pyplot.ylabel('Loss')
        pyplot.xlabel('Epoch -->')
        pyplot.show()

    # Method to create CNN model with different layers and architecture
    @staticmethod
    def create_model():

        # Define and compile the CNN model inside the loop
        model = Sequential([
            Conv2D(16, kernel_size=(2, 2), activation='relu', input_shape=(5, 6, 1)),
            Conv2D(32, kernel_size=(2, 2), activation='relu'),
            Flatten(),
            Dense(64, activation='relu'),
            Dropout(0.3),
            Dense(1, activation='sigmoid')  # binary classification
        ])

        # compile and train
        model.compile(optimizer='adam', loss='mean_squared_logarithmic_error', metrics=['accuracy'])
        return model

    # Method to start creating and running the CNN model
    def run(self):
        # Split into train and test sets
        X_train, X_test, y_train, y_test = train_test_split(self.X_reshaped,
                                                            self.y_onehot,
                                                            test_size=0.2,
                                                            random_state=42)

        if do_kfold_decision:
            # Do k-fold then re-create the inputs and labels
            inputs = np.concatenate((X_train, X_test), axis=0)
            targets = np.concatenate((y_train, y_test), axis=0)

            # K-Fold Class
            kfold = KFold(n_splits=number_of_kfold, random_state=11, shuffle=True)

            # Iterate through each folds
            for train_idx, test_idx in kfold.split(inputs, targets):

                # Create the model
                kfold_model = self.create_model()

                # Train k-fold model with or without early stopping
                if early_stopping_decision:
                    kfold_model.fit(inputs[train_idx], targets[train_idx], epochs=num_epochs_for_kfold, validation_data=(inputs[test_idx], targets[test_idx]), verbose=0, callbacks=[self.callback])
                else:
                    kfold_model.fit(inputs[train_idx], targets[train_idx], epochs=num_epochs_for_kfold, validation_data=(inputs[test_idx], targets[test_idx]), verbose=0)

                # Evaluate the model and get accuracy metrics
                loss_per_fold, accuracy_per_fold = kfold_model.evaluate(inputs[test_idx], targets[test_idx], verbose=0)
                self.kfold_loss.append(loss_per_fold * 100)
                self.kfold_acc.append(accuracy_per_fold * 100)

                # Predict per fold
                y_pred_continuous = kfold_model.predict(X_test, verbose=0)
                y_pred_discrete = np.round(y_pred_continuous).astype(int)

                # Get precision, f1 scores, recall metrics per k-fold
                names = ['Malignant', 'Benign']
                report_per_fold_dic = classification_report(y_test, y_pred_discrete, target_names=names, output_dict=True)
                self.kfold_report.append(pd.DataFrame(report_per_fold_dic).transpose())

        # After using k-fold cross-validation to evaluate your model and tune hyperparameters,
        # the standard practice is not to select one of the models, but to train a final model
        # of the same architecture on the entire available dataset
        final_model = self.create_model()

        # Print the model layers architecture
        if print_summary_decision:
            final_model.summary()

        # Train final model with or without early stopping
        if early_stopping_decision:
            history = final_model.fit(X_train, y_train, epochs=num_epochs_for_final, validation_data=(X_test, y_test), verbose=0, callbacks=[self.callback])
        else:
            history = final_model.fit(X_train, y_train, epochs=num_epochs_for_final, validation_data=(X_test, y_test), verbose=0)

        #   Plot history loss during training of final model
        self.plot_loss_history(history)

        # Prediction using final model
        y_pred_continuous = final_model.predict(X_test, verbose=0)
        y_pred_discrete = np.round(y_pred_continuous).astype(int)

        # Compute the confusion matrix
        # The `labels` parameter ensures the order of classes in the matrix.
        cm = confusion_matrix(y_test, y_pred_discrete)

        # Plot the confusion matrix
        sns.heatmap(cm, annot=True, fmt='g', xticklabels=['Malignant', 'Benign'], yticklabels=['Malignant', 'Benign'])
        pyplot.ylabel('Actual', fontsize=13)
        pyplot.xlabel('Prediction', fontsize=13)
        pyplot.title('Confusion Matrix', fontsize=17, pad=20)
        pyplot.show()

        # Get precision, f1 scores, recall metrics for final model
        names = ['Malignant', 'Benign']
        final_report_dic = classification_report(y_test, y_pred_discrete, target_names=names, output_dict=True)
        self.final_report = pd.DataFrame(final_report_dic).transpose()


# CNN Transformer model
class xformerPredictionModel:

    # Method to initialize the model
    def __init__(self):
        """ init function
        :param:
        :return:
        """
        # Loading dataset
        self.data = load_breast_cancer()
        x = self.data.data      # shape (569, 30)
        y = self.data.target    # 0 or 1 (malignant/benign)

        # Standardize features
        scaler = StandardScaler()
        x_scaled = scaler.fit_transform(x)

        # Reshape for CNN: interpret as 5x6 "images" with 1 channel (since CNN expects 2D data)
        self.X_reshaped = x_scaled.reshape(-1, 5, 6, 1)

        # One-hot encode labels
        lb = LabelBinarizer()
        self.y_onehot = lb.fit_transform(y)

        self.callback = EarlyStopping(
            monitor='val_loss',
            patience=3,
            restore_best_weights=True
        )

        # Storage for metrics
        self.kfold_loss = []
        self.kfold_acc = []
        self.kfold_report = []
        self.final_report = []

    # Method for returning the model's metric
    def get_metrics(self):
        return self.kfold_loss, self.kfold_acc, self.kfold_report, self.final_report

    # Method for plotting loss value for training and validation
    @staticmethod
    def plot_loss_history(history):

        # Plot loss values captured during model training
        pyplot.plot(history.history['loss'], label='Training Dataset')
        pyplot.plot(history.history['val_loss'], label='Testing Dataset')
        pyplot.title('CNN Transformer Epoch Loss History')
        pyplot.legend(("loss", "val_loss"), loc='upper right', shadow=True)
        pyplot.ylabel('Loss')
        pyplot.xlabel('Epoch -->')
        pyplot.show()

    # Build CNN feature extractor
    @staticmethod
    def build_cnn_feature_extractor(input_shape=(5, 6, 1)):

        inputs = keras.Input(shape=input_shape)

        # Simple CNN backbone
        x = layers.Conv2D(32, (3, 3), activation="relu", padding="same")(inputs)
        x = layers.MaxPooling2D((2, 2))(x)
        x = layers.Conv2D(64, (3, 3), activation="relu", padding="same")(x)
        x = layers.MaxPooling2D((2, 2))(x)
        x = layers.Conv2D(128, (3, 3), activation="relu", padding="same")(x)
        x = layers.GlobalAveragePooling2D()(x)

        # Project to embedding dimension for Transformer
        outputs = layers.Dense(128)(x)
        return keras.Model(inputs, outputs, name="cnn_feature_extractor")

    # Transformer encoder block
    @staticmethod
    def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):

        # Multi-head self-attention
        x = layers.MultiHeadAttention(num_heads=num_heads, key_dim=head_size)(inputs, inputs)
        x = layers.Dropout(dropout)(x)
        x = layers.LayerNormalization(epsilon=1e-6)(x + inputs)

        # Feed-forward network
        ff = layers.Dense(ff_dim, activation="relu")(x)
        ff = layers.Dense(inputs.shape[-1])(ff)
        ff = layers.Dropout(dropout)(ff)
        x = layers.LayerNormalization(epsilon=1e-6)(x + ff)
        return x

    # Build CNN and transformer model
    def build_cnn_transformer_model(self, input_shape=(5, 6, 1), num_classes=2):

        # Build cnn feature extractor
        cnn = self.build_cnn_feature_extractor(input_shape)

        inputs = keras.Input(shape=input_shape)
        cnn_features = cnn(inputs)

        # Expand dims to create a "sequence" of length 1 for Transformer
        seq = layers.Reshape((1, cnn_features.shape[-1]))(cnn_features)

        # Apply Transformer encoder layers
        x = self.transformer_encoder(seq, head_size=64, num_heads=4, ff_dim=128, dropout=0.1)
        x = layers.Flatten()(x)

        # Classification head
        outputs = layers.Dense(num_classes, activation="softmax")(x)

        # Create model
        model = keras.Model(inputs, outputs, name="cnn_transformer")

        # TODO mean_squared_logarithmic_error OR sparse_categorical_crossentropy
        model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
        return model

    # Start compile and test
    def run(self):

        # Split into train and test sets
        X_train, X_test, y_train, y_test = train_test_split(self.X_reshaped,
                                                            self.y_onehot,
                                                            test_size=0.2,
                                                            random_state=42)
        if do_kfold_decision:
            # Do k-fold then re-create the inputs and labels
            inputs = np.concatenate((X_train, X_test), axis=0)
            targets = np.concatenate((y_train, y_test), axis=0)

            # K-Fold Class
            kfold = KFold(n_splits=number_of_kfold, random_state=11, shuffle=True)

            # Iterate through folds
            for train_idx, test_idx in kfold.split(inputs, targets):

                # Create a model
                kfold_model = self.build_cnn_transformer_model()

                # Train k-fold model with or without early stopping
                if early_stopping_decision:
                    kfold_model.fit(inputs[train_idx], targets[train_idx], epochs=num_epochs_for_kfold, validation_data=(inputs[test_idx], targets[test_idx]), verbose=0, callbacks=[self.callback])
                else:
                    kfold_model.fit(inputs[train_idx], targets[train_idx], epochs=num_epochs_for_kfold, validation_data=(inputs[test_idx], targets[test_idx]), verbose=0)

                # Evaluate the model and get accuracy metrics
                loss_per_fold, accuracy_per_fold = kfold_model.evaluate(inputs[test_idx], targets[test_idx], verbose=0)
                self.kfold_loss.append(loss_per_fold * 100)
                self.kfold_acc.append(accuracy_per_fold * 100)

                # Predict per fold
                y_pred_continuous = kfold_model.predict(X_test, verbose=0)
                y_pred_discrete = np.argmax(y_pred_continuous, axis=1)

                # Get precision, f1 scores, recall metrics per k-fold
                names = ['Malignant', 'Benign']
                report_per_fold_dic = classification_report(y_test, y_pred_discrete, target_names=names, output_dict=True)
                self.kfold_report.append(pd.DataFrame(report_per_fold_dic).transpose())

        # After using k-fold cross-validation to evaluate your model and tune hyperparameters,
        # the standard practice is not to select one of the models, but to train a final model
        # of the same architecture on the entire available dataset
        final_model = self.build_cnn_transformer_model()

        if print_summary_decision:
            # Print model architecture
            final_model.summary()

        # Train final model with or without early stopping
        if early_stopping_decision:
            history = final_model.fit(X_train, y_train, epochs=num_epochs_for_final, validation_data=(X_test, y_test), verbose=0, callbacks=[self.callback])
        else:
            history = final_model.fit(X_train, y_train, epochs=num_epochs_for_final, validation_data=(X_test, y_test), verbose=0)

        # Plot history loss during training
        self.plot_loss_history(history)

        # Predict of final model
        y_pred_continuous = final_model.predict(X_test, verbose=0)
        predicted_classes = np.argmax(y_pred_continuous, axis=1)

        # Compute the confusion matrix
        # The `labels` parameter ensures the order of classes in the matrix.
        cm = confusion_matrix(y_test, predicted_classes)

        # Plot the confusion matrix
        sns.heatmap(cm, annot=True, fmt='g', xticklabels=['Malignant', 'Benign'], yticklabels=['Malignant', 'Benign'])
        pyplot.ylabel('Actual', fontsize=13)
        pyplot.xlabel('Prediction', fontsize=13)
        pyplot.title('Confusion Matrix', fontsize=17, pad=20)
        pyplot.show()

        # Get precision, f1 scores, recall metrics for final model
        names = ['Malignant', 'Benign']
        report_dic = classification_report(y_test, predicted_classes, target_names=names, output_dict=True)
        self.final_report = pd.DataFrame(report_dic).transpose()


class wilcoxonMetrix:

    @staticmethod
    def calculate(metric_type, cnn, xformer):

        # -----------------------------
        # 1. Wilcoxon Signed-Rank Test
        # -----------------------------
        try:
            stat, p_value = wilcoxon(cnn, xformer, zero_method='zsplit', method='approx')
            print("     For: " + metric_type)
            print(f"            Statistic = {stat}, p-value = {p_value:.5f}")
        except ValueError as e:
            print(f"    Error in Wilcoxon test: {e}")


print("\n********** Run CNN Model and get metrics **********")
cnn_model = cnnPredictionModel()
cnn_model.run()
cnn_kfold_loss, cnn_kfold_acc, cnn_kfold_report, cnn_final_report = cnn_model.get_metrics()
print(f"K-fold Average Accuracy: {np.mean(cnn_kfold_acc):.2f}%")
print(f"K-fold Average loss    : {np.mean(cnn_kfold_loss):.2f}%")

cnn_df = pd.DataFrame()
for i in range(0, number_of_kfold):
    cnn_df = pd.concat([cnn_df, cnn_kfold_report[i]])

cnn_benign = cnn_df.loc['Benign']
cnn_malignant = cnn_df.loc['Malignant']

print("\n********** Run CNN Transformer Model and get metrics **********")
xformer_model = xformerPredictionModel()
xformer_model.run()
xformer_kfold_loss, xformer_kfold_acc, xformer_kfold_report, xformer_final_report = xformer_model.get_metrics()
print(f"K-fold Average Accuracy: {np.mean(xformer_kfold_acc):.2f}%")
print(f"K-fold Average loss    : {np.mean(xformer_kfold_loss):.2f}%")

xformer_df = pd.DataFrame()
for i in range(0, number_of_kfold):
    xformer_df = pd.concat([xformer_df, xformer_kfold_report[i]])

xformer_benign = xformer_df.loc['Benign']
xformer_malignant = xformer_df.loc['Malignant']

print("\n********** Wilcoxon Signed-Rank Test For K-Folds Metrics **********")
metrics = wilcoxonMetrix()
metrics.calculate("Precision for Malignant", cnn_malignant['precision'].tolist(), xformer_malignant['precision'].tolist())
metrics.calculate("Precision for Benign", cnn_benign['precision'].tolist(), xformer_benign['precision'].tolist())

metrics.calculate("Recall for Malignant", cnn_malignant['recall'].tolist(), xformer_malignant['recall'].tolist())
metrics.calculate("Recall for Benign", cnn_benign['recall'].tolist(), xformer_benign['recall'].tolist())

metrics.calculate("f1-score for Malignant", cnn_malignant['f1-score'].tolist(), xformer_malignant['f1-score'].tolist())
metrics.calculate("f1-score for Benign", cnn_benign['f1-score'].tolist(), xformer_benign['f1-score'].tolist())

print("\n********** CNN Final Model Metrics **********")
print(cnn_final_report)

print("\n********** CNN Transformer Model Metrics **********")
print(xformer_final_report)